(()=>{
const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)],clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const imgs={detect:'',research:'',systemize:'',activate:'',learn:''};
const evidenceFiles={detect:'evidence/detect.b64.txt',research:'evidence/research.b64.txt',systemize:'evidence/systemize.b64.txt',activate:'evidence/activate.b64.txt',learn:'evidence/learn.b64.txt'};
async function loadEvidence(){
  await Promise.all(Object.entries(evidenceFiles).map(async([key,path])=>{
    try{
      const res=await fetch(new URL(path,document.baseURI),{cache:'force-cache'});
      if(!res.ok) throw new Error(`evidence ${key}: ${res.status}`);
      const b64=(await res.text()).trim();
      if(!b64) throw new Error(`evidence ${key}: empty`);
      imgs[key]=`data:image/webp;base64,${b64}`;
      const idx=['detect','research','systemize','activate','learn'].indexOf(key);
      if(idx>=0&&stages[idx]) stages[idx].img=imgs[key];
      if(key==='activate'){
        const e=q('[data-eubrics-image]');
        if(e){e.src=imgs[key];e.closest('.project-visual')?.classList.add('loaded')}
      }
      if(idx===lastStage){lastStage=-1;renderStage(idx)}
    }catch(err){console.warn(err)}
  }));
}

const stages=[
 {stage:'Detect',num:'01',title:'Start with movement.',caption:'A real signal creates the reason to look closer.',img:imgs.detect,note:'Historical hiring signal reconstructed; original listing not retained.'},
 {stage:'Research',num:'02',title:'Decide if the account deserves attention.',caption:'Validate fit before spending attention on outreach.',img:imgs.research,note:'Sanitized Clay qualification evidence.'},
 {stage:'Systemize',num:'03',title:'Turn research into reusable inputs.',caption:'Structure the reasoning so the workflow can reuse it.',img:imgs.systemize,note:'Sanitized messaging-input workflow evidence.'},
 {stage:'Activate',num:'04',title:'Let the available data choose the action.',caption:'The next step branches from what is actually known.',img:imgs.activate,note:'Privacy-sanitized outbound branching workflow.'},
 {stage:'Learn',num:'05',title:'A response becomes the next signal.',caption:'Feedback tells the system what to sharpen next.',img:imgs.learn,note:'Privacy-redacted first touch → follow-up → reply.'}
];
function wordify(el){if(!el||el.dataset.wordified)return;let i=0;const walk=n=>{[...n.childNodes].forEach(ch=>{if(ch.nodeType===3&&ch.textContent.trim()){const frag=document.createDocumentFragment();ch.textContent.split(/(\s+)/).forEach(t=>{if(/^\s+$/.test(t)){frag.append(t)}else if(t){const s=document.createElement('span');s.className='aw';s.style.setProperty('--i',i++);s.textContent=t;frag.append(s)}});ch.replaceWith(frag)}else if(ch.nodeType===1)walk(ch)})};walk(el);el.dataset.wordified='1'}
qa('[data-auto-words]').forEach(wordify);const awObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('auto-on');awObs.unobserve(e.target)}}),{threshold:.22});qa('[data-auto-words]').forEach(e=>awObs.observe(e));
const theme=q('button[data-theme]'),light=q('[data-light]'),dark=q('[data-dark]');function paintTheme(){const d=document.documentElement.dataset.theme==='dark';light.classList.toggle('is-active',!d);dark.classList.toggle('is-active',d);try{localStorage.setItem('ak-theme',d?'dark':'light')}catch(e){}}paintTheme();theme.addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';paintTheme()});
const typed=q('[data-typed]');if(typed&&!reduced){const words=['signal','reason','trigger'];let wi=0,ci=0,del=false;const tick=()=>{const w=words[wi];typed.textContent=w.slice(0,ci);if(!del){if(ci<w.length){ci++;setTimeout(tick,88)}else{del=true;setTimeout(tick,1100)}}else{if(ci>0){ci--;setTimeout(tick,48)}else{del=false;wi=(wi+1)%words.length;setTimeout(tick,140)}}};typed.textContent='';tick()}
const jShell=q('.journey-shell'),jCard=q('[data-journey-card]'),jStage=q('[data-j-stage]'),jNum=q('[data-j-num]'),jTitle=q('[data-j-title]'),jCap=q('[data-j-caption]'),jImg=q('[data-j-image]'),jNote=q('[data-j-note]'),jCounter=q('[data-stage-counter]'),labels=qa('[data-label]'),dot=q('[data-stage-dot]'),prog=q('[data-stage-progress]'),stagebar=q('.stagebar');let lastStage=-1;
function renderStage(i){if(i===lastStage)return;lastStage=i;const s=stages[i];jCard.animate([{opacity:.72,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}],{duration:280,easing:'ease-out'});jStage.textContent=s.stage;jNum.textContent=s.num;jTitle.textContent=s.title;jCap.textContent=s.caption;if(s.img){jImg.src=s.img;jImg.style.visibility='visible'}else{jImg.removeAttribute('src');jImg.style.visibility='hidden'}jImg.alt=s.title+' — evidence';jNote.textContent=s.note;jCounter.textContent=`Stage ${s.num} / 05`;labels.forEach((l,x)=>{l.classList.toggle('active',x===i);l.classList.toggle('passed',x<i)})}
function updateJourney(){if(!jShell||innerWidth<=1050){renderStage(0);return}const r=jShell.getBoundingClientRect(),max=jShell.offsetHeight-innerHeight,raw=max?clamp(-r.top/max):0,p=clamp((raw-.045)/.91);const scaled=p*(stages.length-1),i=Math.min(stages.length-1,Math.floor(scaled+1e-7));renderStage(i);if(stagebar&&dot&&prog){const tr=stagebar.getBoundingClientRect(),centers=labels.map(l=>{const x=l.getBoundingClientRect();return x.left+x.width/2-tr.left});const li=Math.min(centers.length-1,Math.floor(scaled)),ri=Math.min(centers.length-1,li+1),local=scaled-li,x=centers[li]+(centers[ri]-centers[li])*local,start=centers[0];dot.style.left=x+'px';prog.style.left=start+'px';prog.style.width=Math.max(0,x-start)+'px';const line=q('.stage-line',stagebar);line.style.left=start+'px';line.style.right=Math.max(0,tr.width-centers.at(-1))+'px'}}renderStage(0);loadEvidence();
const bShell=q('[data-belief-shell]'),bTrack=q('[data-belief-track]'),bCopy=q('[data-belief-copy]');let bWords=[];if(bCopy){const words=bCopy.textContent.trim().split(/\s+/);bCopy.textContent='';words.forEach((w,i)=>{const s=document.createElement('span');s.className='belief-word';if(w.toLowerCase().replace(/[^a-z]/g,'')==='concentrate')s.classList.add('accent');s.textContent=w;bCopy.append(s);bWords.push(s);if(i<words.length-1)bCopy.append(' ')})}
function updateBelief(){if(!bShell||innerWidth<=1050){bTrack.style.transform='none';bWords.forEach(w=>w.classList.add('on'));return}const r=bShell.getBoundingClientRect(),max=bShell.offsetHeight-innerHeight,raw=max?clamp(-r.top/max):0,reveal=clamp(raw/.18),count=Math.floor(reveal*(bWords.length+1));bWords.forEach((w,i)=>w.classList.toggle('on',i<count));const move=clamp((raw-.18)/.76);bTrack.style.transform=`translate3d(${-move*200/3}%,0,0)`}
const fsec=q('.flow-cont'),nodes=qa('[data-step]'),links=qa('[data-link]');let flowRun=false,timers=[];function runFlow(){timers.forEach(clearTimeout);nodes.forEach(n=>n.classList.remove('active','passed'));links.forEach(l=>l.classList.remove('active'));nodes.forEach((n,i)=>timers.push(setTimeout(()=>{nodes.forEach((x,k)=>{x.classList.toggle('active',k===i);x.classList.toggle('passed',k<i)});links.forEach((l,k)=>l.classList.toggle('active',k<i))},i*650)));timers.push(setTimeout(()=>{nodes.forEach(n=>{n.classList.remove('active');n.classList.add('passed')});nodes.at(-1).classList.add('active');links.forEach(l=>l.classList.add('active'))},nodes.length*650))}new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>.52&&!flowRun){flowRun=true;runFlow()}else if(!e.isIntersecting&&e.boundingClientRect.top>innerHeight){flowRun=false}}),{threshold:[0,.52,.75]}).observe(fsec);
const closeShell=q('[data-closing-shell]'),closeTrack=q('[data-closing-track]');function updateClose(){if(!closeShell||innerWidth<=1050){closeTrack.style.transform='none';return}const r=closeShell.getBoundingClientRect(),max=closeShell.offsetHeight-innerHeight,raw=max?clamp(-r.top/max):0;closeTrack.style.transform=`translate3d(${-raw*50}%,0,0)`}
qa('[data-work-jump]').forEach(a=>a.addEventListener('click',e=>{if(innerWidth<=1050)return;e.preventDefault();const y=bShell.getBoundingClientRect().top+scrollY+(bShell.offsetHeight-innerHeight)*.56;scrollTo({top:y,behavior:reduced?'auto':'smooth'})}));qa('[data-talk], [data-talk-secondary]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const y=closeShell.getBoundingClientRect().top+scrollY+(closeShell.offsetHeight-innerHeight)*.98;scrollTo({top:y,behavior:reduced?'auto':'smooth'})}));qa('[data-top]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();scrollTo({top:0,behavior:reduced?'auto':'smooth'})}));q('[data-strategy]')?.addEventListener('click',()=>{const n=q('[data-strategy-note]');n.classList.toggle('open')});
let ticking=false;function update(){updateJourney();updateBelief();updateClose();ticking=false}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(update);ticking=true}},{passive:true});addEventListener('resize',update,{passive:true});update();
})();